app = "spectrace"
primary_region = "sjc"

[build]

[deploy]
  release_command = "python spectrace/manage.py migrate --no-input"

[env]
  DEBUG = "false"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/admin/login/"
    headers = { Host = "spectrace.fly.dev" }

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
