# Generated by Django 5.2.10 on 2026-01-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the test results were imported",
                    ),
                ),
                (
                    "source_file",
                    models.CharField(help_text="Path to JUnit XML file", max_length=500),
                ),
                ("total_tests", models.IntegerField(default=0)),
                ("passed", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Test Run",
                "verbose_name_plural": "Test Runs",
                "ordering": ["-imported_at"],
            },
        ),
        migrations.AddField(
            model_name="requirement",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("passing", "Passing"),
                    ("failing", "Failing"),
                    ("untested", "Untested"),
                ],
                db_index=True,
                default="untested",
                help_text="Verification status based on linked test results",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_nodeid",
                    models.CharField(
                        db_index=True,
                        help_text="pytest nodeid (e.g., tests/test_auth.py::test_login)",
                        max_length=500,
                    ),
                ),
                (
                    "classname",
                    models.CharField(
                        blank=True,
                        help_text="Test class name from JUnit XML",
                        max_length=300,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Test function/method name", max_length=200),
                ),
                (
                    "time",
                    models.FloatField(default=0.0, help_text="Test execution time in seconds"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        help_text="Test result status",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Failure/error message"),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="test_results",
                        to="requirements.requirement",
                    ),
                ),
                (
                    "test_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="requirements.testrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Result",
                "verbose_name_plural": "Test Results",
                "ordering": ["test_nodeid"],
            },
        ),
    ]
