# Generated by Django 5.2.10 on 2026-01-22 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0004_remove_redundant_stored_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier (e.g., 'linear-connection')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Flow description"),
                ),
                (
                    "steps",
                    models.JSONField(default=list, help_text="Ordered list of step definitions"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, help_text="Flow version number"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, help_text="When last synced from code", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Flow",
                "verbose_name_plural": "Verification Flows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VerificationFlowRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="running",
                        help_text="Current execution status",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.JSONField(default=dict, help_text="Execution context and state"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api", "API"),
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="api",
                        help_text="What triggered this run",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, help_text="When execution started"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When execution completed", null=True
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        help_text="The flow that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="requirements.verificationflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Flow Run",
                "verbose_name_plural": "Verification Flow Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationFlowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_order",
                    models.PositiveIntegerField(help_text="Order of execution (0-indexed)"),
                ),
                (
                    "name",
                    models.CharField(help_text="Step name from flow definition", max_length=100),
                ),
                ("passed", models.BooleanField(help_text="Whether the step passed")),
                (
                    "details",
                    models.TextField(blank=True, help_text="Human-readable success details"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error description when step fails"),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True,
                        help_text="HTTP status code if applicable",
                        null=True,
                    ),
                ),
                (
                    "response_body",
                    models.TextField(
                        blank=True, help_text="Sanitized response content for debugging"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When step execution started"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(help_text="When step execution completed"),
                ),
                (
                    "flow_run",
                    models.ForeignKey(
                        help_text="The flow run this step belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="requirements.verificationflowrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Flow Step",
                "verbose_name_plural": "Verification Flow Steps",
                "ordering": ["flow_run", "step_order"],
                "unique_together": {("flow_run", "step_order")},
            },
        ),
    ]
