# Generated by Django 5.2.10 on 2026-01-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0006_inappvalidation_feature_flags_inappvalidation_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='ci_job_url',
            field=models.URLField(blank=True, help_text='URL to CI job that produced this test run', max_length=500),
        ),
        migrations.AddField(
            model_name='testrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When the test run finished', null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='git_branch',
            field=models.CharField(blank=True, help_text='Git branch for this test run', max_length=200),
        ),
        migrations.AddField(
            model_name='testrun',
            name='git_sha',
            field=models.CharField(blank=True, help_text='Git commit SHA for this test run', max_length=40),
        ),
        migrations.AddField(
            model_name='testrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the test run started', null=True),
        ),
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('mutual_exclusion', 'Mutual Exclusion'), ('code_overlap', 'Code Overlap'), ('inverse_correlation', 'Inverse Correlation')], help_text='Type of conflict pattern detected', max_length=50)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Confidence level of the detection', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the conflict (runs analyzed, test results, etc.)')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this conflict has been reviewed and resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the conflict was marked as resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the conflict was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_a', models.ForeignKey(help_text='First requirement in the conflict', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='requirements.requirement')),
                ('requirement_b', models.ForeignKey(help_text='Second requirement in the conflict', on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='requirements.requirement')),
            ],
            options={
                'verbose_name': 'Conflict Log',
                'verbose_name_plural': 'Conflict Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRequirementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_nodeid', models.CharField(db_index=True, help_text='pytest nodeid (e.g., tests/test_auth.py::test_login)', max_length=500)),
                ('last_status', models.CharField(default='unknown', help_text='Status from last test run (passed, failed, error, skipped, unknown)', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When this test was last run', null=True)),
                ('needs_review', models.BooleanField(default=False, help_text='Flag for manual review needed')),
                ('review_reason', models.CharField(blank=True, help_text="Reason for review (e.g., 'flaky', 'new link', 'status changed')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(help_text='The requirement this test verifies', on_delete=django.db.models.deletion.CASCADE, related_name='test_links', to='requirements.requirement')),
            ],
            options={
                'verbose_name': 'Test-Requirement Link',
                'verbose_name_plural': 'Test-Requirement Links',
                'ordering': ['requirement__external_id', 'test_nodeid'],
                'unique_together': {('test_nodeid', 'requirement')},
            },
        ),
    ]
