# Generated by Django 5.2.10 on 2026-02-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0009_add_agent_coordination_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True,
                help_text="Requirements that must be satisfied before this one",
                related_name="depended_by",
                to="requirements.requirement",
            ),
        ),
    ]
