# Generated by Django 5.2.10 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0010_requirement_depends_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationflow",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                help_text="Requirements this flow verifies",
                related_name="verification_flows",
                to="requirements.requirement",
            ),
        ),
    ]
