# Generated by Django 5.2.10 on 2026-02-02 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0011_verificationflow_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(db_index=True, help_text='GitHub delivery ID from X-GitHub-Delivery header', max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text="Event type (e.g., 'workflow_run')", max_length=50)),
                ('action', models.CharField(blank=True, help_text="Event action (e.g., 'completed')", max_length=50)),
                ('repository', models.CharField(db_index=True, help_text='Repository full name (owner/repo)', max_length=200)),
                ('sender', models.CharField(blank=True, help_text='GitHub username that triggered the event', max_length=100)),
                ('payload', models.JSONField(default=dict, help_text='Full webhook payload (sanitized)')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='received', help_text='Processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When webhook was received')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('test_run', models.ForeignKey(blank=True, help_text='TestRun created from this webhook', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='requirements.testrun')),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
    ]
