# Generated by Django 5.2.10 on 2026-02-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0013_test_run_workflow_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirement",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("unclassified", "Unclassified"),
                ],
                db_index=True,
                default="unclassified",
                help_text="Risk classification (critical, high, medium, low)",
                max_length=20,
            ),
        ),
    ]
