# Generated by Django 5.2.10 on 2026-08-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requirements", "0015_intentvalidationresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique ID from the corpus file (e.g., STD-SEC-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("decision", "Decision"),
                            ("commitment", "Commitment"),
                        ],
                        db_index=True,
                        help_text="Kind of obligation (standard, decision, commitment)",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Short descriptive title", max_length=200)),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Team accountable for this entry (e.g., platform)",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Lifecycle state (active, superseded, retired)",
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="Relative path to the corpus markdown file", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Corpus Entry",
                "verbose_name_plural": "Corpus Entries",
                "ordering": ["external_id"],
            },
        ),
        migrations.CreateModel(
            name="CorpusEntryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Version number from the corpus file frontmatter"
                    ),
                ),
                ("body", models.TextField(help_text="Markdown body of the entry at this version")),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 over the versioned content (body, applies_to, checks, metadata)",
                        max_length=64,
                    ),
                ),
                (
                    "applies_to",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validated scope rules (tags, components, paths, requirement_ids)",
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Validated structural checks, each with id, field, operator, value",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date this version takes effect",
                        null=True,
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="Relative path to the corpus markdown file", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The entry this revision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="requirements.corpusentry",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="The entry version this one replaces",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="requirements.corpusentryversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corpus Entry Version",
                "verbose_name_plural": "Corpus Entry Versions",
                "ordering": ["entry__external_id", "-version"],
            },
        ),
        migrations.CreateModel(
            name="CorpusSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "snapshot_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 over the ordered entry version content hashes",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "entry_version_hashes",
                    models.JSONField(
                        default=list,
                        help_text="Ordered content hashes of the member entry versions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "entry_versions",
                    models.ManyToManyField(
                        help_text="Entry versions captured in this snapshot",
                        related_name="snapshots",
                        to="requirements.corpusentryversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corpus Snapshot",
                "verbose_name_plural": "Corpus Snapshots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpecReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "spec_file",
                    models.CharField(
                        blank=True,
                        help_text="Relative path to the reviewed spec file",
                        max_length=500,
                    ),
                ),
                (
                    "reviewer",
                    models.CharField(
                        blank=True, db_index=True, help_text="Who ran the review", max_length=100
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("clean", "Clean"), ("findings", "Findings")],
                        db_index=True,
                        help_text="Whether the review produced findings",
                        max_length=20,
                    ),
                ),
                (
                    "invalidated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When corpus drift made this review stale",
                        null=True,
                    ),
                ),
                (
                    "invalidation_reason",
                    models.TextField(
                        blank=True, help_text="Why this review went stale (entry IDs and versions)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "requirement",
                    models.ForeignKey(
                        help_text="The requirement that was reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corpus_reviews",
                        to="requirements.requirement",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        help_text="Corpus snapshot this review was run against",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="requirements.corpussnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spec Review",
                "verbose_name_plural": "Spec Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "finding_type",
                    models.CharField(
                        choices=[
                            ("unaddressed_obligation", "Unaddressed Obligation"),
                            ("stale_citation", "Stale Citation"),
                            ("orphan_citation", "Orphan Citation"),
                            ("unmet_check", "Unmet Structural Check"),
                            ("conflicting_obligations", "Conflicting Obligations"),
                        ],
                        db_index=True,
                        help_text="Which coverage rule fired",
                        max_length=30,
                    ),
                ),
                (
                    "check_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Check id from the entry's checks block (structural checks only)",
                        max_length=100,
                    ),
                ),
                (
                    "detail",
                    models.TextField(help_text="Deterministic explanation of the rule outcome"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry_version",
                    models.ForeignKey(
                        help_text="The entry version the finding traces to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="requirements.corpusentryversion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="The review that produced this finding",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="requirements.specreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Finding",
                "verbose_name_plural": "Review Findings",
                "ordering": ["entry_version__entry__external_id", "check_id"],
            },
        ),
        migrations.CreateModel(
            name="ReviewCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "matched_by",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Scope rule keys that matched (tags, components, paths, requirement_ids)",
                    ),
                ),
                (
                    "cited",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the spec cites this entry via complies_with",
                    ),
                ),
                (
                    "entry_version",
                    models.ForeignKey(
                        help_text="The entry version that was surfaced",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_rows",
                        to="requirements.corpusentryversion",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        help_text="The review that surfaced this entry version",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage",
                        to="requirements.specreview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Coverage",
                "verbose_name_plural": "Review Coverage",
                "ordering": ["entry_version__entry__external_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="corpusentryversion",
            constraint=models.UniqueConstraint(
                fields=("entry", "version"), name="unique_corpus_entry_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcoverage",
            constraint=models.UniqueConstraint(
                fields=("review", "entry_version"), name="unique_review_coverage_row"
            ),
        ),
    ]
