"""Regenerate the live-state block of docs/current-state.md from the Worker.

`spectrace consolidate` reads the Worker over the v1 API, renders the block
between the `spectrace:auto` markers, and writes the document back. Everything
outside the markers is prose a person maintains.
"""

import re
from datetime import date

BLOCK_START = "<!-- spectrace:auto start (generated by `spectrace consolidate`) -->"
BLOCK_END = "<!-- spectrace:auto end -->"

TASK_STATUSES = (
    "draft",
    "unclaimed",
    "claimed",
    "in_progress",
    "ready_for_review",
    "changes_requested",
    "approved",
    "blocked",
    "merged",
    "abandoned",
)

COVERAGE_COLUMNS = (
    ("Requirements", "total"),
    ("Non-draft", "non_draft"),
    ("Passing", "passing"),
    ("Failing", "failing"),
    ("Untested", "untested"),
    ("Stale", "stale"),
)

_BLOCK = re.compile(
    f"{re.escape(BLOCK_START)}.*?{re.escape(BLOCK_END)}",
    re.DOTALL,
)
_LAST_UPDATED = re.compile(r"Last updated: \d{4}-\d{2}-\d{2}")
_MILESTONE_HEADING = re.compile(
    r"^## (?P<title>v\d+ .+?) \(Shipped: (?P<shipped>\d{4}-\d{2}-\d{2})\)$",
    re.MULTILINE,
)


class BlockMissing(Exception):
    """The document carries no `spectrace:auto` markers to write between."""


def read_live_state(client, project: str | None = None) -> dict:
    """Read coverage and the task ledger from the Worker.

    Args:
        client: A `ValidationClient` pointed at the Worker
        project: Project to report coverage for; the Worker picks when omitted

    Returns:
        {"coverage": SpecCoverage, "tasks": {status: count}}
    """
    params = {"project": project} if project else None
    coverage = _get(client, "/api/v1/specs/coverage", params)["data"]
    tasks = {status: _task_count(client, status) for status in TASK_STATUSES}
    return {"coverage": coverage, "tasks": tasks}


def _get(client, path: str, params: dict | None = None) -> dict:
    response = client.session.get(
        f"{client.api_url}{path}",
        params=params,
        timeout=client.timeout,
    )
    response.raise_for_status()
    return response.json()


def _task_count(client, status: str) -> int:
    page = _get(client, "/api/v1/tasks/", {"status": status, "per_page": 1})
    return page["meta"]["total"]


def milestones_from(planning_record: str) -> list[tuple[str, str]]:
    """Read shipped milestones, newest first, from .planning/MILESTONES.md."""
    return [
        (match.group("title"), match.group("shipped"))
        for match in _MILESTONE_HEADING.finditer(planning_record)
    ]


def render_block(
    *,
    source_url: str,
    generated_on: date,
    coverage: dict,
    tasks: dict[str, int],
    milestones: list[tuple[str, str]],
) -> str:
    """Render the block that sits between the markers."""
    metrics = coverage["metrics"]
    rows = [[coverage["project"], *(str(metrics[key]) for _, key in COVERAGE_COLUMNS)]]
    lines = [
        BLOCK_START,
        "",
        "### Live state",
        "",
        f"Read from {source_url} on {generated_on.isoformat()}.",
        "",
        *_table(["Project", *(header for header, _ in COVERAGE_COLUMNS)], rows),
        "",
        _task_sentence(tasks),
        "",
        "### Shipped milestones",
        "",
        *(f"- {title} ({shipped})" for title, shipped in milestones),
        "",
        BLOCK_END,
    ]
    return "\n".join(lines)


def _task_sentence(tasks: dict[str, int]) -> str:
    held = [f"{count} {status}" for status, count in tasks.items() if count]
    if not held:
        return "The task ledger is empty."
    return f"Task ledger: {', '.join(held)} — {sum(tasks.values())} total."


def _table(headers: list[str], rows: list[list[str]]) -> list[str]:
    widths = [max(len(cell) for cell in column) for column in zip(headers, *rows, strict=True)]
    return [
        _row(headers, widths),
        _row(["-" * width for width in widths], widths),
        *(_row(row, widths) for row in rows),
    ]


def _row(cells: list[str], widths: list[int]) -> str:
    padded = " | ".join(cell.ljust(width) for cell, width in zip(cells, widths, strict=True))
    return f"| {padded} |"


def regenerate(document: str, block: str, generated_on: date) -> str:
    """Replace the marked block and stamp the document's `Last updated` line."""
    if not _BLOCK.search(document):
        raise BlockMissing(f"No {BLOCK_START} … {BLOCK_END} block to regenerate")
    stamped = _LAST_UPDATED.sub(f"Last updated: {generated_on.isoformat()}", document)
    return _BLOCK.sub(lambda _: block, stamped)
