#!/usr/bin/env python3
"""Keep CHANGELOG.md's Unreleased section current with the commit log.

The Unreleased section carries a generated block between markers:

    <!-- changelog:auto since=<ref> -->
    ...generated entries...
    <!-- changelog:/auto -->

The script owns everything between those markers. Prose above the opening
marker and every released section below survive untouched.

Commands:
    update            Regenerate the block from commits since the baseline
    check             Exit 1 when the block is stale (CI and pre-push gate)
    release <version> Promote Unreleased to a dated section, open a fresh one

The baseline defaults to the newest tag. `--since <ref>` overrides it and
records the choice in the marker, so later runs reuse it.

Commits that touch only CHANGELOG.md never appear, which keeps `update`
from generating an entry for its own commit.
"""

import argparse
import difflib
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

CHANGELOG = Path(__file__).parent.parent / "CHANGELOG.md"
PYPROJECT = Path(__file__).parent.parent / "pyproject.toml"

OPEN_MARKER = "<!-- changelog:auto"
CLOSE_MARKER = "<!-- changelog:/auto -->"
MARKER_NOTE = "generated by `make changelog` — edit at release time"
UNRELEASED_HEADING = "## [Unreleased]"

CONVENTIONAL = re.compile(r"^([a-z]+)(\([^)]*\))?(!)?:\s*(.+)$")

SECTIONS = [
    ("breaking", "Breaking changes"),
    ("feat", "Added"),
    ("fix", "Fixed"),
    ("refactor", "Changed"),
    ("docs", "Documentation"),
    ("test", "Tests"),
    ("chore", "Chores"),
    ("other", "Other"),
]

TYPE_TO_SECTION = {
    "feat": "feat",
    "fix": "fix",
    "refactor": "refactor",
    "perf": "refactor",
    "style": "chore",
    "docs": "docs",
    "test": "test",
    "chore": "chore",
    "build": "chore",
    "ci": "chore",
}


def git(*args):
    result = subprocess.run(
        ["git", *args],
        capture_output=True,
        text=True,
        cwd=str(CHANGELOG.parent),
    )
    if result.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout


def newest_tag():
    """Return the highest version tag.

    Sorts by version rather than date: tags created in one batch share a
    creation second, and git falls back to refname order, which puts v0.1.0
    above v0.11.0.
    """
    tags = git("tag", "--sort=-v:refname").split()
    return tags[0] if tags else None


def commits_since(baseline):
    """Return (hash, type, breaking, subject) for each commit after baseline.

    Merges and commits touching only CHANGELOG.md are excluded.
    """
    revision_range = f"{baseline}..HEAD" if baseline else "HEAD"
    raw = git(
        "log",
        revision_range,
        "--no-merges",
        "--reverse",
        "--name-only",
        "--format=%x00%h%x1f%s",
    )

    commits = []
    for record in raw.split("\0"):
        if not record.strip():
            continue
        header, _, body = record.partition("\n")
        commit_hash, _, subject = header.partition("\x1f")
        files = [line for line in body.split("\n") if line.strip()]
        if files == ["CHANGELOG.md"]:
            continue
        commits.append((commit_hash, *classify(subject)))
    return commits


def classify(subject):
    """Return (section key, breaking flag, cleaned subject) for a commit subject."""
    match = CONVENTIONAL.match(subject)
    if not match:
        return "other", False, subject
    commit_type, _, breaking, description = match.groups()
    section = TYPE_TO_SECTION.get(commit_type, "other")
    return section, bool(breaking), description[0].upper() + description[1:]


def render(commits, baseline):
    """Render the generated block, markers included."""
    grouped = {key: [] for key, _ in SECTIONS}
    for commit_hash, section, breaking, subject in commits:
        grouped["breaking" if breaking else section].append(f"- {subject} (`{commit_hash}`)")

    lines = [f"{OPEN_MARKER} since={baseline} ({MARKER_NOTE}) -->", ""]
    body = []
    for key, heading in SECTIONS:
        if grouped[key]:
            body += [f"### {heading}", "", *grouped[key], ""]
    lines += body or ["_Nothing since the last release._", ""]
    lines.append(CLOSE_MARKER)
    return "\n".join(lines)


def split_unreleased(text):
    """Return (before, unreleased body, after) around the Unreleased section."""
    start = text.index(UNRELEASED_HEADING) + len(UNRELEASED_HEADING)
    end = text.index("\n## ", start)
    return text[:start], text[start:end], text[end:]


def read_baseline(body, override):
    if override:
        return override
    match = re.search(rf"{re.escape(OPEN_MARKER)} since=(\S+)", body)
    if match:
        return match.group(1)
    tag = newest_tag()
    if not tag:
        raise SystemExit("No tags found. Pass --since <ref> to set a baseline.")
    return tag


def rebuild(text, since=None):
    before, body, after = split_unreleased(text)
    baseline = read_baseline(body, since)
    block = render(commits_since(baseline), baseline)

    if OPEN_MARKER in body:
        head = body[: body.index(OPEN_MARKER)]
        tail = body[body.index(CLOSE_MARKER) + len(CLOSE_MARKER) :]
    else:
        head, tail = body, "\n"
    return f"{before}{head.rstrip()}\n\n{block}\n{tail.lstrip(chr(10))}{after}"


def cmd_update(args):
    text = CHANGELOG.read_text()
    updated = rebuild(text, args.since)
    if updated == text:
        print("CHANGELOG.md is current.")
        return 0
    CHANGELOG.write_text(updated)
    print("Updated the Unreleased section of CHANGELOG.md.")
    return 0


def cmd_check(args):
    text = CHANGELOG.read_text()
    updated = rebuild(text, args.since)
    if updated == text:
        print("✓ CHANGELOG.md covers every commit since the baseline.")
        return 0
    diff = difflib.unified_diff(
        text.splitlines(keepends=True),
        updated.splitlines(keepends=True),
        fromfile="CHANGELOG.md",
        tofile="expected",
    )
    print("❌ CHANGELOG.md is stale. Run `make changelog`.\n")
    sys.stdout.writelines(diff)
    return 1


def cmd_release(args):
    version = args.version
    text = rebuild(CHANGELOG.read_text(), args.since)
    before, body, after = split_unreleased(text)

    block_start = body.index(OPEN_MARKER)
    entries = body[body.index("-->", block_start) + 3 : body.index(CLOSE_MARKER)].strip()
    curated = body[:block_start].strip()

    released = "\n\n".join(part for part in [curated, entries] if part)
    fresh = render([], version)
    heading = f"## [{version}] — {args.date}"

    CHANGELOG.write_text(f"{before}\n\n{fresh}\n\n{heading}\n\n{released}\n{after.lstrip(chr(10))}")
    print(f"Promoted the Unreleased section to {heading.removeprefix('## ')}.")

    package_version = version.lstrip("v")
    if re.fullmatch(r"\d+\.\d+(\.\d+)*", package_version):
        pyproject = PYPROJECT.read_text()
        PYPROJECT.write_text(
            re.sub(
                r'^version = ".*"', f'version = "{package_version}"', pyproject, count=1, flags=re.M
            )
        )
        print(f"Set pyproject.toml version to {package_version}.")
    else:
        print(f"Left pyproject.toml alone: {version} is a milestone name, not a package version.")

    print(f"Next: review the notes, commit, then `git tag {version}`.")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Keep CHANGELOG.md current with the commit log.")
    parser.add_argument("--since", help="Baseline ref for the generated block")
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("update", help="Regenerate the Unreleased block")
    subparsers.add_parser("check", help="Fail when the Unreleased block is stale")

    release = subparsers.add_parser("release", help="Promote Unreleased to a version")
    release.add_argument("version", help="Version name, such as v11 or 0.2.0")
    release.add_argument("--date", default=date.today().isoformat())

    args = parser.parse_args()
    return {"update": cmd_update, "check": cmd_check, "release": cmd_release}[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
