"""Central constants for the requirements app."""

# API Rate Limits (requests per minute)
RATE_LIMIT_WRITE = "60/m"
RATE_LIMIT_HEAVY_WRITE = "30/m"
RATE_LIMIT_EXTERNAL = "10/m"
RATE_LIMIT_READ = "120/m"

# Request Size Limits
MAX_REQUEST_BODY_SIZE = 5 * 1024 * 1024  # 5MB

# Input Validation Limits
MAX_VALIDATIONS_PER_REQUEST = 500
MAX_STEPS_PER_VALIDATION = 100
MAX_SLOS_PER_REQUEST = 200

# String Length Limits
MAX_REQUIREMENT_ID_LENGTH = 100
MAX_NAME_LENGTH = 500
MAX_MESSAGE_LENGTH = 2000
MAX_URL_LENGTH = 2000
MAX_SOURCE_LENGTH = 200
MAX_STATUS_LENGTH = 20
MAX_VENDOR_LENGTH = 100
MAX_ENDPOINT_LENGTH = 500

# Git Validation
MAX_GIT_REF_LENGTH = 256

# Conflict Detection Thresholds
CONFIDENCE_HIGH_INVERSE_RATIO = 0.8
CONFIDENCE_HIGH_MIN_TESTED = 10
CONFIDENCE_MEDIUM_INVERSE_RATIO = 0.5
CONFIDENCE_MEDIUM_MIN_TESTED = 5
TIMING_RATIO_HIGH = 5
TIMING_RATIO_MEDIUM = 2

# Cache Settings
LINEAR_HEALTH_CACHE_TIMEOUT = 60  # seconds

# Pagination Bounds
MAX_PAGE_NUMBER = 10000
MAX_PER_PAGE = 100
DEFAULT_PER_PAGE = 25

# Corpus Review Finding Types (mirror requirements.models.FindingType values)
FINDING_UNADDRESSED_OBLIGATION = "unaddressed_obligation"
FINDING_STALE_CITATION = "stale_citation"
FINDING_ORPHAN_CITATION = "orphan_citation"
FINDING_UNMET_CHECK = "unmet_check"
FINDING_CONFLICTING_OBLIGATIONS = "conflicting_obligations"
